name: bucketo
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  animated_text_kit: ^4.2.2
  firebase_auth: ^4.17.0
  cloud_firestore: ^4.15.0
  modal_progress_hud_nsn: ^0.5.1
  flutter_slidable: ^3.0.1
  firebase_core: ^2.25.0
  firebase_storage: ^11.6.4
  image_picker: ^1.0.7
  intl: ^0.19.0
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1
  
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true

  assets:
   - assets/
   - assets/images/
   - assets/images/logo.png
