// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgHCMentvHS-1QAPKpQTxerhWTN2w2ADM',
    appId: '1:14249756059:web:fec1df751d91ad1c7e0d3e',
    messagingSenderId: '14249756059',
    projectId: 'bucketo-b3e72',
    authDomain: 'bucketo-b3e72.firebaseapp.com',
    storageBucket: 'bucketo-b3e72.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAldCYvyRzZ_pYQB9ezrMznil_eLgvcl9E',
    appId: '1:14249756059:android:16cc40c2e97235cb7e0d3e',
    messagingSenderId: '14249756059',
    projectId: 'bucketo-b3e72',
    storageBucket: 'bucketo-b3e72.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFukZrV4-hXsRybRoXRgWiOlBsMLL8IRo',
    appId: '1:14249756059:ios:abb07c454480324f7e0d3e',
    messagingSenderId: '14249756059',
    projectId: 'bucketo-b3e72',
    storageBucket: 'bucketo-b3e72.appspot.com',
    iosBundleId: 'com.svntytoo.bucketo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFukZrV4-hXsRybRoXRgWiOlBsMLL8IRo',
    appId: '1:14249756059:ios:a24bcfd5b06873e97e0d3e',
    messagingSenderId: '14249756059',
    projectId: 'bucketo-b3e72',
    storageBucket: 'bucketo-b3e72.appspot.com',
    iosBundleId: 'com.example.bucketo.RunnerTests',
  );
}
